// Config-driven definitions for each pipeline stage page.
// Field types: text | number | currency | date | select | textarea | project | po | schedule | percent(readonly)
// optionsFrom: businessLines | units | salesPics | customers | vendors | projectStatuses

const BL_FIELD = { name: 'businessLine', label: 'Business Line', type: 'select', optionsFrom: 'businessLines', required: true }
const SALES_FIELD = { name: 'salesPic', label: 'Sales PIC', type: 'select', optionsFrom: 'salesPics', allowCustom: true }
const NOTES_FIELD = { name: 'notes', label: 'Notes', type: 'textarea', full: true }

export const STAGES = {
  approaches: {
    key: 'approaches',
    path: '/approach',
    title: 'Approach',
    subtitle: 'Catat lead & follow up sales secara ringkas.',
    cta: 'Tambah Approach',
    emptyTitle: 'Belum ada approach.',
    emptyText: 'Catat lead pertama untuk mulai mengisi pipeline.',
    statuses: ['New', 'Contacted', 'Follow Up', 'Qualified', 'Lost'],
    defaultStatus: 'New',
    docCategory: 'Lainnya',
    hasProject: false,
    filters: ['businessLine', 'status'],
    titleField: 'companyName',
    columns: [
      { key: 'companyName', label: 'Company', primary: true },
      { key: 'customerPic', label: 'PIC' },
      { key: 'salesPic', label: 'Sales PIC' },
      { key: 'businessLine', label: 'Business Line', type: 'bl' },
      { key: 'opportunity', label: 'Opportunity', truncate: true },
      { key: 'approachDate', label: 'Approach Date', type: 'date' },
      { key: 'nextAction', label: 'Next Action', truncate: true },
      { key: 'status', label: 'Status', type: 'status' },
    ],
    mobile: { title: 'companyName', subtitle: 'opportunity', meta: ['salesPic', 'approachDate'] },
    sections: [
      {
        title: 'Customer',
        fields: [
          { name: 'companyName', label: 'Company Name', type: 'text', required: true },
          { name: 'customerPic', label: 'Customer PIC', type: 'text' },
          { name: 'customerContact', label: 'Customer Contact', type: 'text', helper: 'No. HP / email' },
          SALES_FIELD,
          BL_FIELD,
        ],
      },
      {
        title: 'Opportunity',
        fields: [
          { name: 'opportunity', label: 'Need / Opportunity', type: 'text', full: true, required: true },
          { name: 'approachDate', label: 'Approach Date', type: 'date' },
          { name: 'lastFollowUp', label: 'Last Follow Up', type: 'date' },
          { name: 'nextAction', label: 'Next Action', type: 'text', full: true },
        ],
      },
      { title: 'Status', fields: [{ name: 'status', label: 'Status', type: 'status' }, NOTES_FIELD] },
    ],
    detailFields: ['customerPic', 'customerContact', 'salesPic', 'businessLine', 'opportunity', 'approachDate', 'lastFollowUp', 'nextAction', 'notes'],
    actions: [{ id: 'convert', label: 'Buat Penawaran', when: (r) => r.status !== 'Lost' }],
  },

  quotations: {
    key: 'quotations',
    path: '/penawaran',
    title: 'Penawaran',
    subtitle: 'Upload quotation final & isi angka kunci untuk management.',
    cta: 'Tambah Penawaran',
    emptyTitle: 'Belum ada penawaran.',
    emptyText: 'Upload penawaran pertama untuk mulai memantau pipeline.',
    statuses: ['Draft', 'Sent', 'Negotiation', 'Approved', 'Lost'],
    defaultStatus: 'Draft',
    docCategory: 'Quotation',
    hasProject: true,
    allowNewProject: true,
    filters: ['businessLine', 'status'],
    titleField: 'quotationNumber',
    columns: [
      { key: 'quotationNumber', label: 'Quote No', primary: true },
      { key: 'customer', label: 'Customer' },
      { key: 'projectName', label: 'Project', truncate: true },
      { key: 'businessLine', label: 'BL', type: 'bl' },
      { key: 'revenue', label: 'Revenue', type: 'currency' },
      { key: 'hpp', label: 'HPP', type: 'currency' },
      { key: 'margin', label: 'Margin', type: 'currency' },
      { key: 'marginPct', label: 'Margin %', type: 'percent' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'docCount', label: 'File', type: 'docs' },
    ],
    mobile: { title: 'quotationNumber', subtitle: 'customer', value: 'revenue', meta: ['projectName'] },
    sections: [
      {
        title: 'Customer & Project',
        fields: [
          { name: 'projectId', label: 'Project', type: 'project', full: true, helper: 'Pilih project existing, atau kosongkan untuk membuat project baru otomatis.' },
          { name: 'customer', label: 'Customer', type: 'select', optionsFrom: 'customers', allowCustom: true, required: true },
          { name: 'projectName', label: 'Project Name', type: 'text', required: true },
          SALES_FIELD,
          BL_FIELD,
          { name: 'quotationNumber', label: 'Quotation Number', type: 'text', required: true },
          { name: 'quotationDate', label: 'Quotation Date', type: 'date' },
          { name: 'validUntil', label: 'Valid Until', type: 'date' },
          { name: 'unit', label: 'Unit', type: 'select', optionsFrom: 'units' },
        ],
      },
      {
        title: 'Angka Kunci',
        description: 'Margin dihitung otomatis dari Revenue - HPP.',
        fields: [
          { name: 'revenue', label: 'Nilai Project / Revenue', type: 'currency', required: true },
          { name: 'hpp', label: 'HPP / Estimated Cost', type: 'currency' },
          { name: 'margin', label: 'Margin (auto)', type: 'computed', compute: (v) => (Number(v.revenue) || 0) - (Number(v.hpp) || 0), format: 'currency' },
          { name: 'marginPct', label: 'Margin % (auto)', type: 'computed', compute: (v) => (Number(v.revenue) > 0 ? (((Number(v.revenue) || 0) - (Number(v.hpp) || 0)) / Number(v.revenue)) * 100 : 0), format: 'percent' },
        ],
      },
      { title: 'Status', fields: [{ name: 'status', label: 'Status', type: 'status' }, NOTES_FIELD] },
    ],
    detailFields: ['customer', 'projectName', 'salesPic', 'businessLine', 'quotationDate', 'validUntil', 'revenue', 'hpp', 'margin', 'marginPct', 'notes'],
    actions: [{ id: 'convert-po', label: 'Jadikan PO Masuk', when: (r) => r.status === 'Approved' }],
  },

  pos: {
    key: 'pos',
    path: '/po',
    title: 'PO Masuk',
    subtitle: 'PO yang diterima dari customer setelah penawaran disetujui dan menjadi nilai deal final yang diakui perusahaan.',
    cta: 'Tambah PO Masuk',
    emptyTitle: 'Belum ada PO Masuk.',
    emptyText: 'Upload PO Masuk customer pertama untuk mengamankan project.',
    statuses: ['Draft', 'Confirmed', 'Running', 'Completed', 'Cancelled'],
    defaultStatus: 'Confirmed',
    docCategory: 'PO Masuk',
    hasProject: true,
    filters: ['status'],
    titleField: 'poNumber',
    columns: [
      { key: 'poNumber', label: 'Nomor PO Masuk', primary: true },
      { key: 'customer', label: 'Customer' },
      { key: 'project', label: 'Project', type: 'project' },
      { key: 'poDate', label: 'Tanggal PO Masuk', type: 'date' },
      { key: 'poValue', label: 'Nilai Akhir PO', type: 'currency' },
      { key: 'hppFinal', label: 'HPP Final', type: 'currency' },
      { key: 'marginFinal', label: 'Margin Final', type: 'currency' },
      { key: 'marginFinalPct', label: 'Margin Final %', type: 'percent' },
      { key: 'quantity', label: 'Qty', type: 'qty' },
      { key: 'completionPct', label: 'Progress', type: 'progress' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'docCount', label: 'File', type: 'docs' },
    ],
    mobile: { title: 'poNumber', subtitle: 'customer', value: 'poValue', meta: ['poDate'], progress: 'completionPct' },
    sections: [
      {
        title: 'Project & Penawaran',
        fields: [
          { name: 'projectId', label: 'Project', type: 'project', full: true, required: true },
          { name: 'quotationId', label: 'Source Penawaran', type: 'quotation', full: true, required: true, helper: 'PO Masuk harus berasal dari Penawaran yang disetujui.' },
          { name: 'customer', label: 'Customer', type: 'select', optionsFrom: 'customers', allowCustom: true, required: true },
          SALES_FIELD,
          BL_FIELD,
          { name: 'poNumber', label: 'Nomor PO Masuk', type: 'text', required: true },
          { name: 'poDate', label: 'Tanggal PO Masuk', type: 'date', required: true },
          { name: 'vendor', label: 'Vendor (jika ada)', type: 'select', optionsFrom: 'vendors', allowCustom: true },
        ],
      },
      {
        title: 'Nilai Deal Final (Commercial)',
        description: 'Nilai akhir PO dan HPP final menjadi dasar Omzet dan Margin yang diakui perusahaan.',
        fields: [
          { name: 'poValue', label: 'Nilai Akhir PO', type: 'currency', required: true },
          { name: 'hppFinal', label: 'HPP Final', type: 'currency', required: true },
          { name: 'marginFinal', label: 'Margin Final (auto)', type: 'computed', compute: (v) => (Number(v.poValue) || 0) - (Number(v.hppFinal) || 0), format: 'currency' },
          { name: 'marginFinalPct', label: 'Margin Final % (auto)', type: 'computed', compute: (v) => (Number(v.poValue) > 0 ? (((Number(v.poValue) || 0) - (Number(v.hppFinal) || 0)) / Number(v.poValue)) * 100 : 0), format: 'percent' },
          { name: 'quantity', label: 'Quantity', type: 'number' },
          { name: 'unit', label: 'Unit', type: 'select', optionsFrom: 'units' },
        ],
      },
      { title: 'Status', fields: [{ name: 'status', label: 'Status', type: 'status' }, NOTES_FIELD] },
    ],
    detailFields: ['quotationNumber', 'customer', 'salesPic', 'businessLine', 'poDate', 'poValue', 'hppFinal', 'marginFinal', 'marginFinalPct', 'quantity', 'unit', 'vendor', 'deliveredQty', 'remainingQty', 'notes'],
  },

  schedules: {
    key: 'schedules',
    path: '/schedule',
    title: 'Schedule',
    subtitle: 'Progress pengiriman / operasional. Satu PO Masuk bisa banyak schedule.',
    cta: 'Tambah Schedule',
    emptyTitle: 'Belum ada schedule.',
    emptyText: 'Tambahkan jadwal pengiriman pertama untuk PO Masuk yang sudah confirmed.',
    statuses: ['Not Started', 'Scheduled', 'In Transit', 'Partial', 'Delivered', 'Delayed', 'Cancelled'],
    defaultStatus: 'Scheduled',
    docCategory: 'Surat Jalan',
    hasProject: true,
    filters: ['status'],
    titleField: 'deliveryNumber',
    columns: [
      { key: 'deliveryNumber', label: 'Delivery No', primary: true },
      { key: 'project', label: 'Project', type: 'project' },
      { key: 'poNumber', label: 'PO Masuk' },
      { key: 'scheduleDate', label: 'Schedule', type: 'date' },
      { key: 'route', label: 'Rute', type: 'route' },
      { key: 'qty', label: 'Qty', type: 'qty' },
      { key: 'vendor', label: 'Vendor / Armada', truncate: true },
      { key: 'actualDate', label: 'Actual', type: 'date' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'docCount', label: 'File', type: 'docs' },
    ],
    mobile: { title: 'deliveryNumber', subtitle: 'route', meta: ['scheduleDate', 'qtyUnit'] },
    sections: [
      {
        title: 'Project & PO Masuk',
        fields: [
          { name: 'projectId', label: 'Project', type: 'project', required: true },
          { name: 'poId', label: 'PO Masuk', type: 'po', required: true },
          { name: 'deliveryNumber', label: 'Delivery Number', type: 'text', required: true },
          { name: 'scheduleDate', label: 'Schedule Date', type: 'date', required: true },
        ],
      },
      {
        title: 'Pengiriman',
        fields: [
          { name: 'origin', label: 'Origin', type: 'text' },
          { name: 'destination', label: 'Destination', type: 'text' },
          { name: 'qty', label: 'Qty', type: 'number', required: true },
          { name: 'unit', label: 'Unit', type: 'select', optionsFrom: 'units' },
          { name: 'vendor', label: 'Vendor', type: 'select', optionsFrom: 'vendors', allowCustom: true },
          { name: 'armada', label: 'Armada', type: 'text' },
          { name: 'driver', label: 'Driver (opsional)', type: 'text' },
          { name: 'actualDate', label: 'Actual Date', type: 'date' },
        ],
      },
      { title: 'Status', fields: [{ name: 'status', label: 'Delivery Status', type: 'status' }, NOTES_FIELD] },
    ],
    detailFields: ['poNumber', 'scheduleDate', 'actualDate', 'origin', 'destination', 'qty', 'unit', 'vendor', 'armada', 'driver', 'notes'],
  },

  basts: {
    key: 'basts',
    path: '/bast',
    title: 'BAST',
    subtitle: 'Dokumen serah terima. BAST parsial membuat project tetap “Partial”.',
    cta: 'Upload BAST',
    emptyTitle: 'Belum ada BAST.',
    emptyText: 'Upload BAST pertama setelah pengiriman selesai.',
    statuses: ['Draft', 'Uploaded', 'Verified', 'Partial', 'Complete'],
    defaultStatus: 'Uploaded',
    docCategory: 'BAST',
    hasProject: true,
    filters: ['status'],
    titleField: 'bastNumber',
    columns: [
      { key: 'bastNumber', label: 'BAST Number', primary: true },
      { key: 'project', label: 'Project', type: 'project' },
      { key: 'poNumber', label: 'PO Masuk' },
      { key: 'deliveryNumber', label: 'Delivery Ref' },
      { key: 'bastDate', label: 'BAST Date', type: 'date' },
      { key: 'qty', label: 'Qty', type: 'qty' },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'docCount', label: 'File', type: 'docs' },
    ],
    mobile: { title: 'bastNumber', subtitle: 'deliveryNumber', meta: ['bastDate', 'qtyUnit'] },
    sections: [
      {
        title: 'Referensi',
        fields: [
          { name: 'projectId', label: 'Project', type: 'project', required: true },
          { name: 'poId', label: 'PO Masuk', type: 'po', required: true },
          { name: 'deliveryRef', label: 'Delivery Reference', type: 'schedule', full: true, required: true, helper: 'Pilih schedule pengiriman yang diserahterimakan.' },
        ],
      },
      {
        title: 'BAST',
        fields: [
          { name: 'bastNumber', label: 'BAST Number', type: 'text', required: true },
          { name: 'bastDate', label: 'BAST Date', type: 'date', required: true },
          { name: 'qty', label: 'Qty', type: 'number' },
          { name: 'unit', label: 'Unit', type: 'select', optionsFrom: 'units' },
        ],
      },
      { title: 'Status', fields: [{ name: 'status', label: 'Status', type: 'status' }, NOTES_FIELD] },
    ],
    detailFields: ['poNumber', 'deliveryNumber', 'bastDate', 'qty', 'unit', 'notes'],
    docHint: 'Upload BAST utama, lalu tambahkan POD, Surat Jalan, foto, atau dokumen pendukung lainnya.',
  },

  'invoices-in': {
    key: 'invoices-in',
    path: '/invoice-in',
    title: 'Invoice In',
    subtitle: 'Invoice dari vendor → membentuk Utang perusahaan.',
    cta: 'Upload Invoice Vendor',
    emptyTitle: 'Belum ada invoice vendor.',
    emptyText: 'Upload invoice vendor pertama untuk memantau utang.',
    statuses: ['Draft', 'Received', 'Partial Paid', 'Paid', 'Overdue'],
    defaultStatus: 'Received',
    docCategory: 'Invoice',
    hasProject: true,
    filters: ['status'],
    titleField: 'invoiceNumber',
    columns: [
      { key: 'invoiceNumber', label: 'Invoice No', primary: true },
      { key: 'vendor', label: 'Vendor' },
      { key: 'project', label: 'Project', type: 'project' },
      { key: 'poNumber', label: 'PO Masuk' },
      { key: 'invoiceDate', label: 'Invoice Date', type: 'date' },
      { key: 'dueDate', label: 'Due Date', type: 'due' },
      { key: 'amount', label: 'Amount', type: 'currency' },
      { key: 'paidAmount', label: 'Paid', type: 'currency' },
      { key: 'outstanding', label: 'Outstanding', type: 'currency', emphasize: true },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'docCount', label: 'File', type: 'docs' },
    ],
    mobile: { title: 'invoiceNumber', subtitle: 'vendor', value: 'outstanding', valueLabel: 'Outstanding', meta: ['dueDate'] },
    sections: [
      {
        title: 'Project & Vendor',
        fields: [
          { name: 'projectId', label: 'Project', type: 'project', required: true },
          { name: 'poId', label: 'PO Masuk Ref', type: 'po', required: true, helper: 'Invoice In harus mereferensikan PO Masuk.' },
          { name: 'vendor', label: 'Vendor', type: 'select', optionsFrom: 'vendors', allowCustom: true, required: true },
          { name: 'invoiceNumber', label: 'Invoice Number', type: 'text', required: true },
          { name: 'invoiceDate', label: 'Invoice Date', type: 'date', required: true },
          { name: 'dueDate', label: 'Due Date', type: 'date' },
        ],
      },
      {
        title: 'Nilai',
        description: 'Outstanding dihitung otomatis dari Amount - Paid.',
        fields: [
          { name: 'amount', label: 'Amount', type: 'currency', required: true },
          { name: 'paidAmount', label: 'Paid Amount', type: 'currency' },
          { name: 'outstanding', label: 'Outstanding (auto)', type: 'computed', compute: (v) => Math.max(0, (Number(v.amount) || 0) - (Number(v.paidAmount) || 0)), format: 'currency' },
        ],
      },
      { title: 'Status', fields: [{ name: 'status', label: 'Payment Status', type: 'status' }, NOTES_FIELD] },
    ],
    detailFields: ['vendor', 'poNumber', 'invoiceDate', 'dueDate', 'amount', 'paidAmount', 'outstanding', 'notes'],
  },

  'invoices-out': {
    key: 'invoices-out',
    path: '/invoice-out',
    title: 'Invoice Out',
    subtitle: 'Invoice ke customer → membentuk Piutang & penagihan.',
    cta: 'Upload Invoice Customer',
    emptyTitle: 'Belum ada invoice customer.',
    emptyText: 'Upload invoice customer pertama untuk mencatat penagihan & piutang.',
    statuses: ['Draft', 'Sent', 'Partial Paid', 'Paid', 'Overdue'],
    defaultStatus: 'Sent',
    docCategory: 'Invoice',
    hasProject: true,
    filters: ['status'],
    titleField: 'invoiceNumber',
    columns: [
      { key: 'invoiceNumber', label: 'Invoice No', primary: true },
      { key: 'customer', label: 'Customer' },
      { key: 'project', label: 'Project', type: 'project' },
      { key: 'poNumber', label: 'PO Masuk' },
      { key: 'invoiceDate', label: 'Invoice Date', type: 'date' },
      { key: 'dueDate', label: 'Due Date', type: 'due' },
      { key: 'amount', label: 'Amount', type: 'currency' },
      { key: 'paidAmount', label: 'Paid', type: 'currency' },
      { key: 'outstanding', label: 'Outstanding', type: 'currency', emphasize: true },
      { key: 'status', label: 'Status', type: 'status' },
      { key: 'docCount', label: 'File', type: 'docs' },
    ],
    mobile: { title: 'invoiceNumber', subtitle: 'customer', value: 'outstanding', valueLabel: 'Outstanding', meta: ['dueDate'] },
    sections: [
      {
        title: 'Project & Customer',
        fields: [
          { name: 'projectId', label: 'Project', type: 'project', required: true },
          { name: 'poId', label: 'PO Masuk Ref', type: 'po', required: true, helper: 'Invoice Out harus mereferensikan PO Masuk.' },
          { name: 'customer', label: 'Customer', type: 'select', optionsFrom: 'customers', allowCustom: true, required: true },
          { name: 'invoiceNumber', label: 'Invoice Number', type: 'text', required: true },
          { name: 'invoiceDate', label: 'Invoice Date', type: 'date', required: true },
          { name: 'dueDate', label: 'Due Date', type: 'date' },
        ],
      },
      {
        title: 'Nilai',
        description: 'Outstanding dihitung otomatis dari Amount - Paid.',
        fields: [
          { name: 'amount', label: 'Amount', type: 'currency', required: true },
          { name: 'paidAmount', label: 'Paid Amount', type: 'currency' },
          { name: 'outstanding', label: 'Outstanding (auto)', type: 'computed', compute: (v) => Math.max(0, (Number(v.amount) || 0) - (Number(v.paidAmount) || 0)), format: 'currency' },
        ],
      },
      { title: 'Status', fields: [{ name: 'status', label: 'Billing Status', type: 'status' }, NOTES_FIELD] },
    ],
    detailFields: ['customer', 'poNumber', 'invoiceDate', 'dueDate', 'amount', 'paidAmount', 'outstanding', 'notes'],
  },

  stocks: {
    key: 'stocks',
    path: '/stock',
    title: 'Stok',
    subtitle: 'Stok dilaporkan manual. Hanya untuk project yang relevan.',
    cta: 'Tambah Stok',
    emptyTitle: 'Belum ada laporan stok.',
    emptyText: 'Tambahkan item stok jika project Anda memerlukan pemantauan stok.',
    statuses: [],
    docCategory: 'Lainnya',
    hasProject: true,
    filters: [],
    titleField: 'item',
    columns: [
      { key: 'item', label: 'Item / Commodity', primary: true },
      { key: 'project', label: 'Project', type: 'project' },
      { key: 'currentStock', label: 'Current Stock', type: 'qty' },
      { key: 'stockValue', label: 'Stock Value', type: 'currency' },
      { key: 'lastUpdated', label: 'Last Updated', type: 'date' },
      { key: 'docCount', label: 'File', type: 'docs' },
    ],
    mobile: { title: 'item', subtitle: 'notes', value: 'stockValue', meta: ['lastUpdated', 'qtyUnitStock'] },
    sections: [
      {
        title: 'Item',
        fields: [
          { name: 'item', label: 'Item / Commodity', type: 'text', required: true },
          { name: 'projectId', label: 'Project (opsional)', type: 'project' },
          { name: 'currentStock', label: 'Current Stock', type: 'number', required: true },
          { name: 'unit', label: 'Unit', type: 'select', optionsFrom: 'units' },
          { name: 'stockValue', label: 'Stock Value', type: 'currency', required: true },
          { name: 'lastUpdated', label: 'Last Updated', type: 'date' },
          NOTES_FIELD,
        ],
      },
    ],
    detailFields: ['currentStock', 'unit', 'stockValue', 'lastUpdated', 'notes'],
  },
}

export const STAGE_LIST = ['approaches', 'quotations', 'pos', 'schedules', 'basts', 'invoices-in', 'invoices-out']

export const FIELD_LABELS = {
  customer: 'Customer', projectName: 'Project', salesPic: 'Sales PIC', businessLine: 'Business Line', quotationDate: 'Quotation Date', validUntil: 'Valid Until',
  revenue: 'Nilai Penawaran', hpp: 'Estimated HPP', margin: 'Estimated Margin', marginPct: 'Estimated Margin %', notes: 'Notes', customerPic: 'Customer PIC', customerContact: 'Contact', opportunity: 'Opportunity',
  approachDate: 'Approach Date', lastFollowUp: 'Last Follow Up', nextAction: 'Next Action',
  quotationId: 'Source Penawaran', quotationNumber: 'Nomor Penawaran',
  poNumber: 'Nomor PO Masuk', poDate: 'Tanggal PO Masuk', poValue: 'Nilai Akhir PO', hppFinal: 'HPP Final', marginFinal: 'Margin Final', marginFinalPct: 'Margin Final %',
  quantity: 'Qty', unit: 'Unit', vendor: 'Vendor',
  deliveredQty: 'Delivered Qty', remainingQty: 'Remaining Qty', scheduleDate: 'Schedule Date', actualDate: 'Actual Date', origin: 'Origin', destination: 'Destination',
  qty: 'Qty', armada: 'Armada', driver: 'Driver', deliveryNumber: 'Delivery Ref', bastDate: 'BAST Date', invoiceDate: 'Invoice Date', dueDate: 'Due Date', amount: 'Amount', paidAmount: 'Paid Amount',
  outstanding: 'Outstanding', currentStock: 'Current Stock', stockValue: 'Stock Value', lastUpdated: 'Last Updated',
}

export const CURRENCY_FIELDS = new Set(['revenue', 'hpp', 'margin', 'poValue', 'hppFinal', 'marginFinal', 'amount', 'paidAmount', 'outstanding', 'stockValue'])
export const DATE_FIELDS = new Set(['quotationDate', 'validUntil', 'approachDate', 'lastFollowUp', 'poDate', 'scheduleDate', 'actualDate', 'bastDate', 'invoiceDate', 'dueDate', 'lastUpdated'])
export const ACTUAL_DATE_FIELDS = new Set(['approachDate', 'lastFollowUp', 'quotationDate', 'poDate', 'actualDate', 'bastDate', 'invoiceDate', 'paymentDate', 'lastUpdated'])
export const FUTURE_ALLOWED_DATE_FIELDS = new Set(['validUntil', 'scheduleDate', 'dueDate'])
export const PCT_FIELDS = new Set(['marginPct', 'marginFinalPct'])
export const QTY_FIELDS = new Set(['quantity', 'qty', 'deliveredQty', 'remainingQty', 'currentStock'])

